# This version of config.mk was generated by:
# ./configure --enable-curses
# Any changes made here will be lost if configure is re-run
SRCDIR = .
PREFIX = /usr/local
EXEC_PREFIX = $(PREFIX)
BINDIR = $(EXEC_PREFIX)/bin
DOCPREFIX = $(PREFIX)/share/doc
MANPREFIX = $(PREFIX)/share/man
SHAREPREFIX = $(PREFIX)/share
CC = musl-gcc
CFLAGS = -pipe -Os -ffunction-sections -fdata-sections -fPIC
LDFLAGS = -Wl,-z,now -Wl,-z,relro
CFLAGS_STD = -std=c99 -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -DNDEBUG -D_FORTIFY_SOURCE=2 -I/usr/local/musl/include
LDFLAGS_STD = -static
CFLAGS_AUTO = -fstack-protector-all
LDFLAGS_AUTO = -Wl,--gc-sections 
CFLAGS_DEBUG = -U_FORTIFY_SOURCE -UNDEBUG -O0 -g -ggdb -Wall -Wextra -pedantic -Wno-missing-field-initializers -Wno-unused-parameter
CONFIG_HELP = 1
CFLAGS_TERMKEY = 
LDFLAGS_TERMKEY = -ltermkey
CONFIG_CURSES = 1
CFLAGS_CURSES = -D_GNU_SOURCE -D_DEFAULT_SOURCE
LDFLAGS_CURSES = /usr/local/musl/lib/libncursesw.a /usr/local/musl/lib/libtermcap.a /usr/local/musl/lib/libterminfo.a /usr/local/musl/lib/libunibilium.a
REGEX_SRC = text-regex-tre.c
CONFIG_TRE = 1
CFLAGS_TRE = -D_FORTIFY_SOURCE=2
LDFLAGS_TRE = /usr/local/musl/lib/libtre.a -Wl,-O1,--sort-common,--as-needed,-z,relro
CONFIG_LUA = 1
CFLAGS_LUA =  -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -DLUA_COMPAT_ALL
LDFLAGS_LUA = /usr/local/musl/lib/liblua.a -lm -llua
CONFIG_LPEG = 1
CFLAGS_LPEG = 
LDFLAGS_LPEG = /usr/local/musl/lib/liblpeg.a
CONFIG_ACL = 0
CFLAGS_ACL = 
#LDFLAGS_ACL = -lacl
CONFIG_SELINUX = 0
CFLAGS_SELINUX = 
LDFLAGS_SELINUX = 
CFLAGS_LIBC = -DHAVE_MEMRCHR=1
